# Generated by Django 5.2.2 on 2025-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifymodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
