# Generated by Django 5.2.2 on 2025-06-06 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notifymodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifymodel',
            name='programe_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
