# Generated by Django 5.2.2 on 2025-06-06 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notifymodel_programe_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifymodel',
            name='programe_time',
        ),
        migrations.AddField(
            model_name='notifymodel',
            name='programe_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 11, 3, 29, 696752, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
