# Generated by Django 5.2.2 on 2025-06-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_notifymodel_programe_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifymodel',
            old_name='programe_date',
            new_name='program_date',
        ),
    ]
