# Generated by Django 5.2.1 on 2025-06-13 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_programe_date_notifymodel_program_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('collection_date', models.DateField()),
                ('collection_type', models.CharField(choices=[('Weekly Collection', 'Weekly Collection'), ('Monthly Collection', 'Monthly Collection'), ('Special Collection', 'Special Collection')], max_length=100)),
                ('image', models.ImageField(upload_to='media/finance/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
