# Generated by Django 5.2.1 on 2025-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_financemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financemodel',
            name='title',
        ),
    ]
