# Generated by Django 5.2.3 on 2025-06-15 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_financemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemodel',
            name='announced_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
