# Generated by Django 5.2.3 on 2025-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_financemodel_announced_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitReceiverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('family', models.TextField()),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='kit/')),
            ],
        ),
        migrations.AlterField(
            model_name='financemodel',
            name='image',
            field=models.ImageField(upload_to='finance/'),
        ),
    ]
