# Generated by Django 5.2.3 on 2025-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_kitreceivermodel_announced_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitreceivermodel',
            name='location',
            field=models.URLField(max_length=255),
        ),
    ]
