# Generated by Django 5.2.3 on 2025-09-13 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='AnnouncementModel',
        ),
    ]
