# Generated by Django 5.2.3 on 2025-09-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_announcement_announcementmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementmodel',
            old_name='announced_time',
            new_name='announced_date',
        ),
    ]
