# Generated by Django 5.2.1 on 2025-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_announced_time_announcementmodel_announced_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
