# Generated by Django 5.2.1 on 2025-09-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_announcementmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
