# Generated by Django 5.2.1 on 2025-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_announcementmodel_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
