# Generated by Django 5.2.1 on 2025-09-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_announcementmodel_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifymodel',
            name='department',
            field=models.CharField(blank=True, choices=[('bba', 'BBA'), ('bca', 'BCA'), ('bsc_cs', 'BSc CS'), ('bcom_tax', 'BCom Tax'), ('ttm', 'TTM'), ('bcom_ca_and_finance', 'BCom CA and Finance'), ('bcom_co_operation', 'BCom Co-operation'), ('ba_literature', 'BA Literature'), ('ba_communicative_english', 'BA Communicative English'), ('ba_journalism', 'BA Journalism'), ('electronics', 'Electronics'), ('bsw', 'BSW')], max_length=50, null=True),
        ),
    ]
