# Generated by Django 5.2.1 on 2025-09-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_notifymodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifymodel',
            name='priority_duty',
            field=models.CharField(blank=True, choices=[('Finance', 'Finance'), ('Collection Team', 'Collection Team')], max_length=20, null=True),
        ),
    ]
