# Generated by Django 5.2.1 on 2025-09-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_notifymodel_priority_duty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifymodel',
            name='announced_time',
        ),
        migrations.RemoveField(
            model_name='notifymodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='notifymodel',
            name='priority_duty',
        ),
        migrations.CreateModel(
            name='NotifyModelPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('bba', 'BBA'), ('bca', 'BCA'), ('bsc_cs', 'BSc CS'), ('bcom_tax', 'BCom Tax'), ('ttm', 'TTM'), ('bcom_ca_and_finance', 'BCom CA and Finance'), ('bcom_co_operation', 'BCom Co-operation'), ('ba_literature', 'BA Literature'), ('ba_communicative_english', 'BA Communicative English'), ('ba_journalism', 'BA Journalism'), ('electronics', 'Electronics'), ('bsw', 'BSW')], max_length=50, null=True)),
                ('priority_duty', models.CharField(blank=True, choices=[('Finance', 'Finance'), ('Collection Team', 'Collection Team')], max_length=20, null=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('announced_time', models.DateTimeField(auto_now_add=True)),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.notifymodel')),
            ],
        ),
    ]
