# Generated by Django 5.2.1 on 2025-09-20 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_notifymodelpriority_readed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('Weekly Collection', 'Weekly Collection'), ('Event Based Collection', 'Event Based Collection'), ('Special Collection', 'Special Collection')])),
                ('description', models.TextField()),
                ('collection_date', models.DateField()),
                ('announced_date', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('image', models.ImageField(upload_to='finance/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
