# Generated by Django 5.2.1 on 2025-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_collectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
