# Generated by Django 5.2.1 on 2025-09-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_collectionmodel_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/')),
            ],
        ),
        migrations.RemoveField(
            model_name='collectionmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='dashboard.collectiongallerymodel'),
        ),
    ]
