# Generated by Django 5.2.3 on 2025-09-23 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_collectiongallerymodel_remove_collectionmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifymodel',
            name='announced_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
