# Generated by Django 5.1.4 on 2026-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_notifymodel_announced_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='collection_type',
            field=models.CharField(choices=[('Weekly Collection', 'Weekly Collection'), ('Event Based Collection', 'Event Based Collection'), ('Special Collection', 'Special Collection')], max_length=100),
        ),
        migrations.AlterField(
            model_name='financemodel',
            name='collection_type',
            field=models.CharField(choices=[('Weekly Collection', 'Weekly Collection'), ('Monthly Collection', 'Monthly Collection'), ('Special Collection', 'Special Collection')], max_length=100),
        ),
    ]
