# Generated by Django 5.2.1 on 2025-05-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenier', '0002_pendingmemberaddrequest'),
        ('members', '0011_remove_memberregistration_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmemberaddrequest',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingmemberaddrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.memberregistration'),
        ),
    ]
