# Generated by Django 5.2.1 on 2025-05-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenier', '0003_pendingmemberaddrequest_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingmemberaddrequest',
            old_name='message',
            new_name='reason',
        ),
    ]
