# Generated by Django 5.2.1 on 2025-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenier', '0005_alter_pendingmemberaddrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmemberaddrequest',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
    ]
