# Generated by Django 5.2.1 on 2025-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenier', '0006_pendingmemberaddrequest_ispending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingmemberaddrequest',
            name='isPending',
            field=models.BooleanField(default=False),
        ),
    ]
