# Generated by Django 5.2.3 on 2025-09-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenier', '0007_alter_pendingmemberaddrequest_ispending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='convinierModel',
        ),
    ]
