# Generated by Django 5.1.4 on 2026-03-06 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=7)),
                ('card_no', models.CharField(max_length=16)),
                ('name_on_card', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, null=True)),
                ('donated_date', models.DateField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
