# Generated by Django 5.2.1 on 2025-09-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_donation_donationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.CharField(),
        ),
    ]
