# Generated by Django 5.2.3 on 2025-09-20 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_donationmodel_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='donated_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
