# Generated by Django 5.2.3 on 2025-09-20 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_donationmodel_donated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
