# Generated by Django 5.2.1 on 2025-05-18 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adno', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('bba', 'BBA'), ('bca', 'BCA'), ('bsc_cs', 'BSc CS'), ('bcom_tax', 'BCom Tax'), ('ttm', 'TTM'), ('bcom_ca_and_finance', 'BCom CA and Finance'), ('bcom_co_operation', 'BCom Co-operation'), ('ba_literature', 'BA Literature'), ('ba_communicative_english', 'BA Communicative English'), ('ba_journalism', 'BA Journalism'), ('electronics', 'Electronics'), ('bsw', 'BSW')], max_length=50)),
                ('batch', models.CharField(max_length=10)),
                ('current_year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
