# Generated by Django 5.1.4 on 2026-05-09 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0004_alter_coordinateregistration_current_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING_CONVENER', 'Pending Convener Approval'), ('PENDING_PRINCIPAL', 'Pending Principal Approval'), ('PENDING_CHAIRMAN', 'Pending Chairman Approval'), ('APPROVED', 'Approved'), ('REJECTED_TO_CONVENER', 'Rejected to Convener')], default='PENDING_CONVENER', max_length=50)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
