# Generated by Django 5.1.4 on 2026-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coordinateregistration',
            name='department',
            field=models.CharField(choices=[('bba', 'BBA'), ('bca', 'BCA'), ('bsc_cs', 'BSc CS'), ('bcom_tax', 'BCom Tax'), ('ttm', 'TTM'), ('bcom_ca_and_finance', 'BCom CA and Finance'), ('bcom_co_operation', 'BCom Co-operation'), ('ba_literature', 'BA Literature'), ('ba_communicative_english', 'BA Literature'), ('ba_communicative_english', 'BA Communicative English'), ('ba_journalism', 'BA Journalism'), ('electronics', 'Electronics'), ('bsw', 'BSW')], max_length=50),
        ),
    ]
