# Generated by Django 5.1.4 on 2026-05-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_faq_alter_coordinateregistration_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
