# Generated by Django 5.2.1 on 2025-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='batch',
            field=models.CharField(default='2023-2026', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='current_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='department',
            field=models.CharField(choices=[('bca', 'BCA'), ('bba', 'BBA')], default='ba', max_length=20),
            preserve_default=False,
        ),
    ]
