# Generated by Django 5.2.1 on 2025-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberregistration_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='current_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=5),
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='department',
            field=models.CharField(choices=[('bba', 'BBA'), ('bca', 'BCA'), ('bsc_cs', 'BSC CS'), ('bcom_tax', 'bcom tax'), ('ttm', 'ttm'), ('bcom_ca_and_finance', 'bcom ca and finance'), ('bcom_co-operation', 'bcom co-operation'), ('ba_literature', 'ba literature'), ('ba_communicative_english', 'ba_communicative_english'), ('ba_journalism', 'ba_journalism'), ('electronics', 'electronics'), ('bsw', 'bsw')]),
        ),
    ]
