# Generated by Django 5.2.1 on 2025-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_mcregistration_delete_memberregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcregistration',
            name='current_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mcregistration',
            name='department',
            field=models.CharField(choices=[('bba', 'BBA'), ('bca', 'BCA'), ('bsc_cs', 'BSc CS'), ('bcom_tax', 'BCom Tax'), ('ttm', 'TTM'), ('bcom_ca_and_finance', 'BCom CA and Finance'), ('bcom_co_operation', 'BCom Co-operation'), ('ba_literature', 'BA Literature'), ('ba_communicative_english', 'BA Communicative English'), ('ba_journalism', 'BA Journalism'), ('electronics', 'Electronics'), ('bsw', 'BSW')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mcregistration',
            name='duty',
            field=models.CharField(choices=[('No Duty', 'No Duty'), ('Finance', 'Finance'), ('Collection Team', 'Collection Team'), ('Event Organizers', 'Event Organizers'), ('Mini Coordination', 'Mini Coordination')], default='No Duty', max_length=50),
        ),
    ]
