# Generated by Django 5.2.1 on 2025-05-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_mcregistration_current_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcregistration',
            name='duty',
        ),
        migrations.CreateModel(
            name='memberRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(choices=[('No Duty', 'No Duty'), ('Finance', 'Finance'), ('Collection Team', 'Collection Team'), ('Event Organizers', 'Event Organizers'), ('Mini Coordination', 'Mini Coordination')], default='No Duty', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.mcregistration')),
            ],
        ),
    ]
