# Generated by Django 5.2.1 on 2025-05-18 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_mcregistration_duty_memberregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='adno',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='batch',
            field=models.CharField(default=-3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='current_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='department',
            field=models.CharField(choices=[('bba', 'BBA'), ('bca', 'BCA'), ('bsc_cs', 'BSc CS'), ('bcom_tax', 'BCom Tax'), ('ttm', 'TTM'), ('bcom_ca_and_finance', 'BCom CA and Finance'), ('bcom_co_operation', 'BCom Co-operation'), ('ba_literature', 'BA Literature'), ('ba_communicative_english', 'BA Communicative English'), ('ba_journalism', 'BA Journalism'), ('electronics', 'Electronics'), ('bsw', 'BSW')], default='bca', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
