# Generated by Django 5.2.1 on 2025-05-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_memberregistration_adno_memberregistration_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCRegistration',
        ),
    ]
