# Generated by Django 5.2.1 on 2025-05-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_delete_mcregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
