# Generated by Django 5.2.1 on 2025-05-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_memberregistration_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberregistration',
            name='isApproved',
        ),
    ]
