# Generated by Django 5.2.1 on 2025-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_memberregistration_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='duty',
            field=models.CharField(choices=[('No Duty', 'No Duty'), ('Finance', 'Finance'), ('Collection Team', 'Collection Team'), ('Event Organizers', 'Event Organizers'), ('Team Controller', 'Team Controller')], default='No Duty', max_length=50),
        ),
    ]
