# Generated by Django 5.2.1 on 2025-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_memberregistration_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='current_year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=10),
        ),
    ]
