# Generated by Django 5.2.1 on 2025-05-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_memberregistration_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='current_year',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=15),
        ),
    ]
