# Generated by Django 5.1.4 on 2026-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_memberregistration_adno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='membership_decided_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Active'), ('volunteer', 'Moved to Volunteer'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
