# Generated by Django 5.1.4 on 2026-05-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
