# Generated by Django 5.1.4 on 2026-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteer_approved_by_volunteer_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
