# Generated by Django 5.1.4 on 2026-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_volunteer_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
