# Generated by Django 5.1.4 on 2026-04-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_campaign_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='period',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='end_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='start_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='batch',
            field=models.CharField(blank=True, choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('BSc CS', 'BSc CS'), ('BCom', 'BCom'), ('BA', 'BA'), ('BSW', 'BSW')], max_length=20, null=True),
        ),
    ]
