# Generated by Django 5.1.4 on 2026-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0011_volunteer_was_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='end_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='start_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
