# Generated by Django 5.1.4 on 2026-05-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_alter_volunteer_end_year_alter_volunteer_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
