# Generated by Django 5.1.4 on 2026-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0013_volunteer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
