# Generated by Django 5.1.4 on 2026-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_age_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('public_user', 'public_user'), ('member', 'member'), ('coordinator', 'coordinator'), ('convenier', 'convenier'), ('office_staff', 'office_staff'), ('principal', 'principal'), ('chairman', 'chairman')], default='public_user', max_length=20),
        ),
    ]
